import nextPlugin from "@next/eslint-plugin-next";
import tseslintParser from "@typescript-eslint/parser";

const eslintConfig = [
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    languageOptions: {
      parser: tseslintParser,
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        alert: "readonly",
        URL: "readonly",
        Blob: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        process: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        global: "readonly",
        Promise: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        ReferenceError: "readonly",
        SyntaxError: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Symbol: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        Intl: "readonly",
        AbortController: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        URLSearchParams: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly",
        performance: "readonly",
        crypto: "readonly",
        atob: "readonly",
        btoa: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
        encodeURI: "readonly",
        decodeURI: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        parseFloat: "readonly",
        parseInt: "readonly",
        escape: "readonly",
        unescape: "readonly",
        eval: "readonly",
        Function: "readonly",
        Infinity: "readonly",
        NaN: "readonly",
        undefined: "readonly",
        null: "readonly",
        true: "readonly",
        false: "readonly",
        React: "readonly",
        useState: "readonly",
        useEffect: "readonly",
        useMemo: "readonly",
        useCallback: "readonly",
        useRef: "readonly",
        useContext: "readonly",
        useReducer: "readonly",
        use: "readonly",
        createContext: "readonly",
        forwardRef: "readonly",
        useId: "readonly",
        useLayoutEffect: "readonly",
        useImperativeHandle: "readonly",
        useDebugValue: "readonly",
        useDeferredValue: "readonly",
        useTransition: "readonly",
        useSyncExternalStore: "readonly",
        useInsertionEffect: "readonly",
        memo: "readonly",
        lazy: "readonly",
        Suspense: "readonly",
        Fragment: "readonly",
        StrictMode: "readonly",
        Profiler: "readonly",
        Children: "readonly",
        PureComponent: "readonly",
        Component: "readonly",
      },
    },
    plugins: {
      "@next/next": nextPlugin,
    },
    rules: {
      "@next/next/no-html-link-for-pages": "off",
      "react/no-unescaped-entities": "off",
      "no-unused-vars": "off",
      "no-undef": "off",
      "no-redeclare": "off",
    },
  },
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "dist/**",
      "coverage/**",
      "prisma/**",
    ],
  },
];

export default eslintConfig;
